networks:
  dev:
    driver: bridge

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=User ID =postgres;Password=postgres;Server=postgres;Port=5432;Database=SampleDb;Pooling=true;
    image: server-dotnet-image
    container_name: dotnet
    depends_on:
      - postgres
    networks:
      - dev

  client:
    image: angular-client-image
    container_name: angular
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - server

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SampleDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - dev

volumes:
  postgres_data:
