version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    image: server-dotnet-image
    depends_on:
      postgres:
        condition: service_healthy

  client:
    image: angular-client-image
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - server

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: behshad
      POSTGRES_PASSWORD: password
      POSTGRES_DB: behshad
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U behshad -d behshad"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
